/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;
import Clases.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACalix
 */
public class GEmpleados extends javax.swing.JInternalFrame {
    private boolean agregando=false;
    private int posicionElemento ;
    /**
     * Creates new form GEmpleados
     */
    public GEmpleados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtEdad = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        BEliminar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        BGuardar = new javax.swing.JButton();
        BEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaEmpleados = new javax.swing.JTable();
        BtNuevo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();

        setClosable(true);
        setResizable(true);
        setTitle("Registro de Empleados");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Nombre:");

        BEliminar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8-cancel-48.png"))); // NOI18N
        BEliminar.setText("Eliminar");
        BEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEliminarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Apellidos:");

        BGuardar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8-save-48.png"))); // NOI18N
        BGuardar.setText("Guardar");
        BGuardar.setEnabled(false);
        BGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BGuardar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGuardarActionPerformed(evt);
            }
        });

        BEditar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8-edit-property-48.png"))); // NOI18N
        BEditar.setText("Editar");
        BEditar.setEnabled(false);
        BEditar.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        BEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEditarActionPerformed(evt);
            }
        });

        TablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellidos", "Edad", "Direccion", "Telefono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaEmpleados);

        BtNuevo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8-add-list-48.png"))); // NOI18N
        BtNuevo.setText("Nuevo");
        BtNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtNuevo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtNuevoActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8-administrator-male-48.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Direccion:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Telefono:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("ID:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Edad:");

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(BtNuevo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BEliminar)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(136, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BEditar)
                            .addComponent(BGuardar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                        .addGap(23, 23, 23)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtNuevo)
                            .addComponent(BGuardar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BEliminar)
                            .addComponent(BEditar)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(70, 70, 70))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGuardarActionPerformed
        // TODO add your handling code here:
         if(agregando){
           int id,edad;
        String nombre,apellidos,telefono,direccion;
        
        id = Integer.parseInt(this.txtId.getText());
        edad = Integer.parseInt(this.txtEdad.getText());
        nombre = this.txtNombre.getText();
        apellidos = this.txtApellidos.getText();
        direccion = this.txtDireccion.getText();
        telefono = this.txtTelefono.getText();
        Empleados empleado = new Empleados();
        empleado.setId(id);
        empleado.setNombre(nombre);
        empleado.setEdad(edad);
        empleado.setApellidos(apellidos);
        empleado.setDireccion(direccion);
        empleado.setTelefono(telefono);

        PantallaPrincipal.empleado.agregarEmpleado(empleado);
        
        actualizarElementosEnTabla();
        this.agregando=false; 
        }
        else{
        int id,edad;
        String nombre,apellidos,telefono,direccion;
      
        id=Integer.parseInt(this.txtId.getText());
        edad=Integer.parseInt(this.txtEdad.getText());
        nombre=this.txtNombre.getText();
        apellidos=this.txtApellidos.getText();
        direccion=this.txtDireccion.getText();
        telefono = this.txtTelefono.getText();
        
        Empleados empleadoModificado=new Empleados();
        empleadoModificado.setId(id);
        empleadoModificado.setNombre(nombre);
        empleadoModificado.setEdad(edad);
        empleadoModificado.setApellidos(apellidos);
        empleadoModificado.setTelefono(telefono);
        empleadoModificado.setDireccion(direccion);
        
        PantallaPrincipal.empleado.modificarEmpleado(empleadoModificado, this.posicionElemento);
        this.actualizarElementosEnTabla();
        }
        this.BGuardar.setEnabled(false);
        this.BtNuevo.setEnabled(true);
        this.BEditar.setEnabled(true);
       
    }                                        

    private void tablaEmpleadosMousePressed(java.awt.event.MouseEvent evt) {                                            
        // TODO add your handling code here:
          this.posicionElemento=this.TablaEmpleados.getSelectedRow();
   
        Empleados empleado=PantallaPrincipal.empleado.get(posicionElemento);
        this.txtId.setText(Integer.toString(empleado.getId()));
        this.txtNombre.setText(empleado.getNombre());
        this.txtApellidos.setText(empleado.getApellidos());
        this.txtEdad.setText(Integer.toString(empleado.getEdad()));
        this.txtDireccion.setText(empleado.getDireccion());
        this.txtTelefono.setText(empleado.getTelefono());
        this.BEditar.setEnabled(true);
    }                                           
    public void actualizarElementosEnTabla(){
        try{
        String[] tituloColumnas={"Id","Nombre","Apellidos","Edad","Telefono","Direccion"};
        DefaultTableModel d=new DefaultTableModel(PantallaPrincipal.empleado.getArrayGestion(),tituloColumnas);
    
        this.TablaEmpleados.setModel(d);
	//AdminSerializacion.guardar(PantallaPrincipal.gEmpleado, "Empleado.obj");
        }catch(Exception e){
            
        }		
        
    }
    private void BNuevoActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code he
    }//GEN-LAST:event_BGuardarActionPerformed

    private void BtNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtNuevoActionPerformed
        // TODO add your handling code here:
        this.agregando = true;
        this.BGuardar.setEnabled(true);
        this.BtNuevo.setEnabled(false);
        this.BEditar.setEnabled(false);
    }//GEN-LAST:event_BtNuevoActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void BEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEliminarActionPerformed
        // TODO add your handling code here:
         if (JOptionPane.showConfirmDialog(this, "Esta seguro?", "Confirmación", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
            PantallaPrincipal.empleado.eliminarEmpleado(this.posicionElemento);
            this.actualizarElementosEnTabla();
        }
    }//GEN-LAST:event_BEliminarActionPerformed

    private void BEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEditarActionPerformed
        // TODO add your handling code here:
        this.agregando = false;
        this.BGuardar.setEnabled(true);
        this.BtNuevo.setEnabled(false);
        this.BEditar.setEnabled(false);
    }//GEN-LAST:event_BEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BEditar;
    private javax.swing.JButton BEliminar;
    private javax.swing.JButton BGuardar;
    private javax.swing.JButton BtNuevo;
    private javax.swing.JTable TablaEmpleados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
