/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Clases.ListaEmpleado;
import Recursos.Fondo;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author ACalix
 */
public class PantallaPrincipal extends javax.swing.JFrame {
    public static ListaEmpleado empleado=new ListaEmpleado();
    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        desktopPane.setBorder(new Fondo());
        this.setMinimumSize(new Dimension(928, 521));
        this.setLocationRelativeTo(null);
     
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        BVenta = new javax.swing.JButton();
        BEmpleados = new javax.swing.JButton();
        BInventario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(255, 255, 255));

        BVenta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8-shopping-basket-80.png"))); // NOI18N
        BVenta.setText("Ventas");
        BVenta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BVenta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        desktopPane.add(BVenta);
        BVenta.setBounds(170, 290, 113, 109);

        BEmpleados.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8-user-groups-80.png"))); // NOI18N
        BEmpleados.setText("Empleados");
        BEmpleados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BEmpleados.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEmpleadosActionPerformed(evt);
            }
        });
        desktopPane.add(BEmpleados);
        BEmpleados.setBounds(610, 290, 113, 109);

        BInventario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8-open-box-80.png"))); // NOI18N
        BInventario.setText("Almacen");
        BInventario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BInventario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        desktopPane.add(BInventario);
        BInventario.setBounds(390, 290, 113, 109);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 928, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEmpleadosActionPerformed
        // TODO add your handling code here:
        GEmpleados empleado=new GEmpleados();
        empleado.setVisible(true);
        Dimension jInternalFrameSize = empleado.getSize();//Obtiene de las dimensiones del internalFrame
        Dimension desktopSize = this.getSize(); //Obtiene las dimensiones desktop 
        empleado.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
               (desktopSize.height - jInternalFrameSize.height) / 2);
        this.desktopPane.add(empleado);
        empleado.toFront();
    }//GEN-LAST:event_BEmpleadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BEmpleados;
    private javax.swing.JButton BInventario;
    private javax.swing.JButton BVenta;
    private javax.swing.JDesktopPane desktopPane;
    // End of variables declaration//GEN-END:variables

}
